ADDED:User_reg_form
NavinAT/TraineeWorkSamples pull request #11
Opened 2023-03-09 09:38 UTC by PrakashVjr

User  Registration Form Initial

2023-03-09 12:13 UTC, NavinAT requested changes
Reviewed your code please change and give the new pull request.

Please check the `<form>` tag path i couldn't run the project.
Please provide a proper run able solution then i can check the process

Thanks.

2023-03-09 12:13 UTC, NavinAT commented on Prakash/User_reg_form/style2.css
> +    padding: 0;
Indent the code properly

2023-03-10 05:44 UTC, PrakashVjr commented on Prakash/User_reg_form/edit.html
> +
test

2023-03-10 05:47 UTC, PrakashVjr commented
Resolved closed by naveen

2023-03-10 05:47 UTC, closed without merging