ADDED:Mail Validation and style modification in all pages.
NavinAT/TraineeWorkSamples pull request #13
Opened 2023-03-10 10:21 UTC by sivabalan18102001

2023-03-15 14:03 UTC, NavinAT requested changes
I have reviewed your changes and added some comment..

Thanks.

2023-03-15 14:03 UTC, NavinAT commented on Sivabalan/15-02-2023 Task/User Edit Page.html
1. Validation error not showing
2. remove button enlarge style.
3. Change button border radius - refer button style in bootstrap [https://getbootstrap.com/docs/4.0/components/buttons/](url)

2023-03-16 04:25 UTC, sivabalan18102001 commented on Sivabalan/15-02-2023 Task/Detail page Script.js
> +                if(0<numberofuser && valid)
completed

2023-03-16 04:31 UTC, sivabalan18102001 commented on Sivabalan/15-02-2023 Task/Detail page Script.js
> +        if(arr[0]==null)
completed

2023-03-16 04:50 UTC, sivabalan18102001 commented on Sivabalan/15-02-2023 Task/Main page Script.js
> +        }
Checked

2023-03-16 04:50 UTC, sivabalan18102001 commented on Sivabalan/15-02-2023 Task/Main page Script.js
> +{
Completed

2023-03-16 04:53 UTC, sivabalan18102001 commented on Sivabalan/15-02-2023 Task/Main page Script.js
> +window.open("Next page.html", '_blank');
Completed

2023-03-16 04:55 UTC, sivabalan18102001 commented on Sivabalan/15-02-2023 Task/Next page.html
> +      <script src="Detail page Script.js"></script>
It write the details inside the table at that place. So script is added in this place.

2023-03-16 04:56 UTC, sivabalan18102001 commented on Sivabalan/15-02-2023 Task/User Edit Page.html
> +    <script src="Edit page Script.js"></script>
Completed

2023-03-16 04:56 UTC, sivabalan18102001 commented on Sivabalan/15-02-2023 Task/Style for Next second page.css
> +tr:hover{
Completed

2023-03-16 04:57 UTC, sivabalan18102001 commented on Sivabalan/15-02-2023 Task/Style for Next second page.css
> +body
Completed

2023-03-17 04:23 UTC, merged